
// This file was automatically generated by wchgen. More information at:
//
// https://github.com/dadleyy/orient-beetle/tree/master/tools/wchgen
const char * index_html PROGMEM = "HTTP/1.1 200 Ok\r\nContent-Length: 213\r\n\r\n<!doctype html><html lang='en'><head><title>...</title></head><body><form action='/' method='post'><input type='text' name='ssid' /><input type='text' name='password' /><input type='submit' /></form></body></html>";
