[package]
name = "beetle-srv"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
dotenv = { version = "^0.15" }
env_logger = { version = "^0.9" }
log = { version = "^0.4" }
tide = { version = "^0.16" }
async-std = { version = "^1.0", features = ["attributes"] }
async-tls = { version = "^0.10" }
kramer = { version = "^1.1", features = ["kramer-async"] }
