name: build-and-publish
on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/beetle-srv
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: cargo build
      - name: test
        run: cargo test

  build-pio:
    runs-on: ubuntu-latest
    env:
      BEETLE_GPG_KEY: "${{ secrets.BEETLE_CI_GPG }}"
      REDIS_HOST: "${{ secrets.PIO_REDIS_HOST }}"
      REDIS_PORT: "${{ secrets.PIO_REDIS_PORT }}"
      REDIS_AUTH_USERNAME: "${{ secrets.PIO_REDIS_AUTH_USERNAME }}"
      REDIS_AUTH_PASSWORD: "${{ secrets.PIO_REDIS_AUTH_PASSWORD }}"
    defaults:
      run:
        working-directory: src/beetle-pio
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: "set output: short_sha"
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: "import gpg"
        run: "echo \"${{ secrets.BEETLE_CI_GPG }}\" > orient-beetle-ci.key && gpg --import orient-beetle-ci.key && rm orient-beetle-ci.key"

      - name: "pip: upgrade"
        run: python -m pip install --upgrade pip
      - name: "pip: install pio"
        run: pip install --upgrade platformio
      - name: "env prep: fill redis ca"
        run: echo $REDIS_HOST_ROOT_CA > embeds/redis_host_root_ca.pem
      - name: "pio: run"
        run: pio run -e release

      - name: "ls: platformio -> tools"
        run: ls -lah $HOME/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/bin
      - name: "ls: platformio -> partitions"
        run: ls -lah $HOME/.platformio/packages/framework-arduinoespressif32/tools/partitions

      - name: "bundle: prepare-dir"
        run: mkdir -p beetle-pio-dist

      - name: "bundle: copy-bin"
        run: gpg --trust-model always -e -r 99D22D47AA5053FC -o beetle-pio-dist/firmware.bin.pgp .pio/build/release/firmware.bin
      - name: "bundle: copy-map"
        run: gpg --trust-model always -e -r 99D22D47AA5053FC -o beetle-pio-dist/firmware.map.pgp .pio/build/release/firmware.map
      - name: "bundle: copy-elf"
        run: gpg --trust-model always -e -r 99D22D47AA5053FC -o beetle-pio-dist/firmware.elf.pgp .pio/build/release/firmware.elf
      - name: "bundle: copy-partitions"
        run: gpg --trust-model always -e -r 99D22D47AA5053FC -o beetle-pio-dist/partitions.bin.pgp .pio/build/release/partitions.bin
      - name: "bundle: copy-bootloader"
        run: gpg --trust-model always -e -r 99D22D47AA5053FC -o beetle-pio-dist/bootloader.bin.pgp $HOME/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/bin/bootloader_dio_40m.bin
      - name: "bundle: copy-apploader"
        run: gpg --trust-model always -e -r 99D22D47AA5053FC -o beetle-pio-dist/apploader.bin.pgp $HOME/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin

      - name: "bundle: create"
        run: tar cvzf beetle-pio-${{ steps.vars.outputs.sha_short }}.tar.gz beetle-pio-dist

      - uses: actions/upload-artifact@v3
        with:
          name: "beetle-pio-${{ steps.vars.outputs.sha_short }}.tar.gz"
          path: "./src/beetle-pio/beetle-pio-${{ steps.vars.outputs.sha_short }}.tar.gz"

  build-ui:
    runs-on: ubuntu-latest
    env:
      BEETLE_VERSION: "${{ github.sha }}"
      # note: These are specific paths related to nginx hosting config. When developing locally,
      # it is more likely you will be serving from a root `/`.
      BEETLE_UI_ROOT: "/beetle/"
      BEETLE_API_ROOT: "/beetle/api/"
      BEETLE_LOGIN_URL: "https://www.krumpled.com/beetle/api/auth/redirect"
    defaults:
      run:
        working-directory: src/beetle-ui
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: "set output: short_sha"
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: "install elm: download"
        run: curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz

      - name: "install elm: unpack"
        run: gunzip elm.gz && chmod +x elm

      - name: "install elm: install"
        run: sudo mv elm /usr/local/bin/

      - name: "install elm: verison"
        run: elm --version

      - name: "install node-deps"
        run: npm i

      - name: "lint: ts"
        run: npm run lint:ts

      - name: "lint: elm"
        run: npm run lint:elm -- --validate

      - name: "make: release"
        run: make release

      - name: prepare-bundle
        run: mv target/release beetle-ui-dist

      - name: create-bundle
        run: tar cvzf beetle-ui-${{ steps.vars.outputs.sha_short }}.tar.gz beetle-ui-dist

      - uses: actions/upload-artifact@v3
        with:
          name: "beetle-ui-${{ steps.vars.outputs.sha_short }}.tar.gz"
          path: "./src/beetle-ui/beetle-ui-${{ steps.vars.outputs.sha_short }}.tar.gz"

  build-srv-osx:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-12
    env:
      BEETLE_VERSION: "${{ github.sha }}"
    defaults:
      run:
        working-directory: src/beetle-srv
    steps:
      - uses: actions/checkout@v2
      - name: "set output: short_sha"
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: "build"
        run: cargo build --release
      - name: "bundle: prepare"
        run: mkdir -p beetle-server-dist/bin
      - name: "bundle: cli"
        run: cp target/release/beetle-cli beetle-server-dist/bin/beetle-cli
      - name: "bundle: create"
        run: tar cvzf beetle-server-osx-${{ steps.vars.outputs.sha_short }}.tar.gz beetle-server-dist
      - uses: actions/upload-artifact@v3
        with:
          name: "beetle-server-osx-${{ steps.vars.outputs.sha_short }}.tar.gz"
          path: "./src/beetle-srv/beetle-server-osx-${{ steps.vars.outputs.sha_short }}.tar.gz"

  build-srv-armv7:
    runs-on: ubuntu-latest
    env:
      BEETLE_VERSION: "${{ github.sha }}"
    container:
      image: dadleyy/rust-raspberry-pi-openssl:latest
    defaults:
      run:
        working-directory: src/beetle-srv
    steps:
      - uses: actions/checkout@v2
      - name: "set output: short_sha"
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: build
        run: cargo build --target armv7-unknown-linux-gnueabihf --release
        env:
          OPENSSL_LIB_DIR: /tmp/openssl-1.1.1g/
          OPENSSL_INCLUDE_DIR: /tmp/openssl-1.1.1g/include

      - name: prepare-bundle
        run: mkdir -p beetle-server-dist/bin

      - name: "populate-bundle: cli"
        run: cp target/armv7-unknown-linux-gnueabihf/release/beetle-cli beetle-server-dist/bin/beetle-cli

      - name: "populate-bundle: web"
        run: cp target/armv7-unknown-linux-gnueabihf/release/beetle-web beetle-server-dist/bin/beetle-web

      - name: "populate-bundle: registrar"
        run: cp target/armv7-unknown-linux-gnueabihf/release/beetle-registrar beetle-server-dist/bin/beetle-registrar

      - name: create-bundle
        run: tar cvzf beetle-server-armv7-unknown-linux-gnueabihf-${{ steps.vars.outputs.sha_short }}.tar.gz beetle-server-dist

      - uses: actions/upload-artifact@v3
        with:
          name: "beetle-server-armv7-unknown-linux-gnueabihf-${{ steps.vars.outputs.sha_short }}.tar.gz"
          path: "./src/beetle-srv/beetle-server-armv7-unknown-linux-gnueabihf-${{ steps.vars.outputs.sha_short }}.tar.gz"

  build-updater:
    runs-on: ubuntu-latest
    container:
      image: dadleyy/rust-raspberry-pi-openssl:latest
    defaults:
      run:
        working-directory: tools/beetle-updater
    steps:
      - uses: actions/checkout@v2
      - name: "set output: short_sha"
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: "clippy: install"
        run: rustup component add clippy
      - name: "clippy: run"
        run: cargo clippy

      - name: build
        run: cargo build --target armv7-unknown-linux-gnueabihf --release
        env:
          OPENSSL_LIB_DIR: /tmp/openssl-1.1.1g/
          OPENSSL_INCLUDE_DIR: /tmp/openssl-1.1.1g/include
          BEETLE_UPDATER_VERSION: ${{ steps.vars.outputs.sha_short }}

      - name: prepare-bundle
        run: mkdir -p beetle-updater-dist/bin

      - name: "populate-bundle"
        run: cp target/armv7-unknown-linux-gnueabihf/release/beetle-srv-updater beetle-updater-dist/bin/

      - name: create-bundle
        run: tar cvzf beetle-updater-armv7-unknown-linux-gnueabihf-${{ steps.vars.outputs.sha_short }}.tar.gz beetle-updater-dist

      - uses: actions/upload-artifact@v3
        with:
          name: "beetle-updater-armv7-unknown-linux-gnueabihf-${{ steps.vars.outputs.sha_short }}.tar.gz"
          path: "./tools/beetle-updater/beetle-updater-armv7-unknown-linux-gnueabihf-${{ steps.vars.outputs.sha_short }}.tar.gz"

  publish:
    runs-on: ubuntu-latest
    needs: ["build-srv-armv7", "build-srv-osx", "build-ui", "build-pio", "build-updater"]
    steps:
      - uses: actions/checkout@v2
      - name: "set output: short_sha"
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - uses: actions/download-artifact@v3
        with:
          name: "beetle-updater-armv7-unknown-linux-gnueabihf-${{ steps.vars.outputs.sha_short }}.tar.gz"

      - uses: actions/download-artifact@v3
        with:
          name: "beetle-server-armv7-unknown-linux-gnueabihf-${{ steps.vars.outputs.sha_short }}.tar.gz"

      - uses: actions/download-artifact@v3
        with:
          name: "beetle-ui-${{ steps.vars.outputs.sha_short }}.tar.gz"

      - uses: actions/download-artifact@v3
        with:
          name: "beetle-pio-${{ steps.vars.outputs.sha_short }}.tar.gz"

      - name: printall
        run: ls -lah

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "./*.tar.gz"
          generate_release_notes: true
          body_path: ${{ github.workspace }}/.automation/release-body.md
