name: client
on:
  push:
  create:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BEETLE_VERSION: "${{ github.sha }}"
      BEETLE_UI_ROOT: "/beetle"
      BEETLE_API_ROOT: "/beetle/api/"
    defaults:
      run:
        working-directory: src/beetle-ui
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: "install elm: download"
        run: curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz

      - name: "install elm: unpack"
        run: gunzip elm.gz && chmod +x elm

      - name: "install elm: install"
        run: sudo mv elm /usr/local/bin/

      - name: "install elm: verison"
        run: elm --version

      - name: "install node-deps"
        run: npm i

      - name: "lint: ts"
        run: npm run ts:lint

      - name: "make: release"
        run: make release

      - name: prepare-bundle
        run: mv target/release beetle-ui-dist

      - name: create-bundle
        run: tar cvzf beetle-ui-$BEETLE_VERSION.tar.gz beetle-ui-dist

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "./src/beetle-ui/beetle-ui-${{ github.sha }}.tar.gz"
